### ISSUE TITLE
Task 1: Create a signup page (frontend)

### ISSUE THREAD

**Issue by micahwib** [hack4impact-calpoly/HumaneSociety#6]
We want to allow users to signup and create an account. They should input first & last name, email, phone number, and password. 

- [ ] Create a signup page based on the design in [Figma](https://www.figma.com/file/feT5mgD78QjSxo7C0nLJzi/H4I%3A-Woods-Project?node-id=0%3A1) 
- [ ] Work with the person responsible for the backend to connect to the backend endpoint to push data to MongoDB cluster (Task 3 & 4)
- [ ] Make it is mobile compatible
- [ ] If needed utilize the [Material-UI library](https://mui.com/getting-started/installation/) (will need to npm install the package)

**Comment by S0han** [comment]
id would like to give this a shot

**Comment by sameerabali5** [comment]
@S0han would you like to work together?
