### ISSUE TITLE
Task 5: Create Password Reset and Password Page (frontend)

### ISSUE THREAD

**Issue by micahwib** [hack4impact-calpoly/HumaneSociety#7]
We want to allow the user to reset their password if they forget.

- [ ] Create a forgot & reset password based on the design in [Figma](https://www.figma.com/file/feT5mgD78QjSxo7C0nLJzi/H4I%3A-Woods-Project?node-id=0%3A1) 
- [ ] Work with the login frontend dev to add the forgot password page to their page (Task  2)
- [ ] Make it is mobile compatible
- [ ] If needed utilize the [Material-UI library](https://mui.com/getting-started/installation/) (will need to npm install the package)
Note: No backend endpoints will be made just yet.

**Comment by riyaz4s** [comment]
@micahwib Can i take up this issue ?

**Comment by micahwib** [comment]
> @micahwib Can i take up this issue ?

Unfortunately, I have already assigned the task to someone.
