### ISSUE TITLE
Task 51: Debug AWS/ mongoDB confirm email

### ISSUE THREAD

**Issue by micahwib** [hack4impact-calpoly/HumaneSociety#90]
Sometimes when signing up and after the user confirms their email, they try to sign in and still get the "please confirm your email". Try to find the reason why and fix it.

Could be after someone changes their password?

- [ ] Debug the confirm email

**Comment by sleepyStick** [comment]
tried a few things to reproduce the bug:
- created new account; tried to log in without verification (saw confirm email msg as expected), verified email and was successfully able to login without seeing the message
- tried to reset password and then login again, also didn't see message
